{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-dependency-prebuilt",
    "version": "0.1.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency-mapper",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-prebuilt-0.1.0-LOCAL.jar",
          "url": "toolkit-dependency-prebuilt-0.1.0-LOCAL.jar",
          "size": 105570,
          "sha512": "609c6bde7babc6d03f42e7284905500f404170ca3979e1d10ec149f9b6e722290e385a801aa76e942a04febd3f57ef3ed850b7ae0505e2e09cc5411013408ddc",
          "sha256": "3c7dbe389ed069df3f26423d3e3bc54158131fa7268e53880ff5a2534f9b3d04",
          "sha1": "e8d8bc371f569313107c3859b49745be1ddda4bb",
          "md5": "a9a4de0ecdb3f77c14c4cdb50a9a7530"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-apache",
          "version": {
            "requires": "1.6.6",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.6",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency-mapper",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-prebuilt-0.1.0-LOCAL.jar",
          "url": "toolkit-dependency-prebuilt-0.1.0-LOCAL.jar",
          "size": 105570,
          "sha512": "609c6bde7babc6d03f42e7284905500f404170ca3979e1d10ec149f9b6e722290e385a801aa76e942a04febd3f57ef3ed850b7ae0505e2e09cc5411013408ddc",
          "sha256": "3c7dbe389ed069df3f26423d3e3bc54158131fa7268e53880ff5a2534f9b3d04",
          "sha1": "e8d8bc371f569313107c3859b49745be1ddda4bb",
          "md5": "a9a4de0ecdb3f77c14c4cdb50a9a7530"
        }
      ]
    }
  ]
}
