{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-dependency-prebuilt",
    "version": "0.1.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency-mapper",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-prebuilt-0.1.0-LOCAL.jar",
          "url": "toolkit-dependency-prebuilt-0.1.0-LOCAL.jar",
          "size": 131790,
          "sha512": "4316558abf98127afecf9dca72fe6502d577e4e0af16e23be41745780212b87c2595c7d38ff9019a318e1ad7ea6b2de9d01dc0abd3d846d9c29c905fdea0415b",
          "sha256": "62593ed417615a23655c04080bf04d803a9e5b7a0eee30c6cd926955cd3d77c7",
          "sha1": "9e155f402b469a78ad41c9e22f933732c4590db1",
          "md5": "749b744308c73423e8d643d3592bdbb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-apache",
          "version": {
            "requires": "1.6.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency-mapper",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-prebuilt-0.1.0-LOCAL.jar",
          "url": "toolkit-dependency-prebuilt-0.1.0-LOCAL.jar",
          "size": 131790,
          "sha512": "4316558abf98127afecf9dca72fe6502d577e4e0af16e23be41745780212b87c2595c7d38ff9019a318e1ad7ea6b2de9d01dc0abd3d846d9c29c905fdea0415b",
          "sha256": "62593ed417615a23655c04080bf04d803a9e5b7a0eee30c6cd926955cd3d77c7",
          "sha1": "9e155f402b469a78ad41c9e22f933732c4590db1",
          "md5": "749b744308c73423e8d643d3592bdbb1"
        }
      ]
    }
  ]
}
