{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-dependency-updater",
    "version": "0.1.0-LOCAL-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-updater-0.1.0-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-dependency-updater-0.1.0-LOCAL-SNAPSHOT.jar",
          "size": 553901,
          "sha512": "a95ca3c0304f66947a9fedc02fc91b47de3e2a11a9c85248fedf0c14d3625cfa13658da26110c3add3ea24e53dc11d446d637218f9ea6b73bf077e9d85826db5",
          "sha256": "dd49eb699470d88838e2dd8a8ab9a3e07e4d8f5f6577048aba719e132295715b",
          "sha1": "fecab52c66827ec8527294f1472c52c556a53e20",
          "md5": "a2480178807c9bf7e7a20b40e2a600df"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-storage",
          "version": {
            "requires": "2.1.5",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.12.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0",
            "rejects": [
              "_"
            ]
          },
          "reason": "It has ready to use HttpException class"
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "strictly": "30.1.1-jre",
            "requires": "30.1.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-updater-0.1.0-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-dependency-updater-0.1.0-LOCAL-SNAPSHOT.jar",
          "size": 553901,
          "sha512": "a95ca3c0304f66947a9fedc02fc91b47de3e2a11a9c85248fedf0c14d3625cfa13658da26110c3add3ea24e53dc11d446d637218f9ea6b73bf077e9d85826db5",
          "sha256": "dd49eb699470d88838e2dd8a8ab9a3e07e4d8f5f6577048aba719e132295715b",
          "sha1": "fecab52c66827ec8527294f1472c52c556a53e20",
          "md5": "a2480178807c9bf7e7a20b40e2a600df"
        }
      ]
    }
  ]
}
