{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-core",
    "version": "0.1.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "be.vbgn.gradle",
          "module": "ci-detect-plugin",
          "version": {
            "requires": "0.5.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-0.1.0-LOCAL.jar",
          "url": "toolkit-core-0.1.0-LOCAL.jar",
          "size": 362968,
          "sha512": "9c476306bdc26bd2deaae9877a36a5032443275660de788f5148b90a3ede7554cee51015a703f2799a864d9f296c8d29628b70a9b75a1891631ed5df41961ff1",
          "sha256": "f3a6ccf688514efab0e24408fd585a8db1cd76d64ed57c7e12e06bf2b10b9fbc",
          "sha1": "e6617cee00a82367f35eca3f9c947c9779a7bb02",
          "md5": "1d7a2b000a8f8663e26f30959dc40141"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "be.vbgn.gradle",
          "module": "ci-detect-plugin",
          "version": {
            "requires": "0.5.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-0.1.0-LOCAL.jar",
          "url": "toolkit-core-0.1.0-LOCAL.jar",
          "size": 362968,
          "sha512": "9c476306bdc26bd2deaae9877a36a5032443275660de788f5148b90a3ede7554cee51015a703f2799a864d9f296c8d29628b70a9b75a1891631ed5df41961ff1",
          "sha256": "f3a6ccf688514efab0e24408fd585a8db1cd76d64ed57c7e12e06bf2b10b9fbc",
          "sha1": "e6617cee00a82367f35eca3f9c947c9779a7bb02",
          "md5": "1d7a2b000a8f8663e26f30959dc40141"
        }
      ]
    }
  ]
}
