{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-core",
    "version": "0.1.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "be.vbgn.gradle",
          "module": "ci-detect-plugin",
          "version": {
            "requires": "0.5.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-0.1.0-LOCAL.jar",
          "url": "toolkit-core-0.1.0-LOCAL.jar",
          "size": 373443,
          "sha512": "342bcf55526533c7ee23a3d3030139712c12bf156ad32128a2eccef92b389ecf8344416c314cef6cd0fca1cf0201ab823cefd11ccd9552fbac0d9587f00926b2",
          "sha256": "a550f589364376427ff79adf7adaeefccbb0b5ab2148f30cf494f827197ec207",
          "sha1": "88bbec1748528d874decb4989ddb59e1bc05c00b",
          "md5": "96059404ccfa051be007415da0e3c719"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "be.vbgn.gradle",
          "module": "ci-detect-plugin",
          "version": {
            "requires": "0.5.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-0.1.0-LOCAL.jar",
          "url": "toolkit-core-0.1.0-LOCAL.jar",
          "size": 373443,
          "sha512": "342bcf55526533c7ee23a3d3030139712c12bf156ad32128a2eccef92b389ecf8344416c314cef6cd0fca1cf0201ab823cefd11ccd9552fbac0d9587f00926b2",
          "sha256": "a550f589364376427ff79adf7adaeefccbb0b5ab2148f30cf494f827197ec207",
          "sha1": "88bbec1748528d874decb4989ddb59e1bc05c00b",
          "md5": "96059404ccfa051be007415da0e3c719"
        }
      ]
    }
  ]
}
