{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-dependency",
    "version": "0.2.2-LOCAL-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency-mapper",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency-updater",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency-prebuilt",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-dependency-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 261,
          "sha512": "d82ce997efde752f0dfa6de421193dc1505f11d58e86843d6f31e203e34357da2ff048476e742935e0262757a76e1601633a1bae4b3d17939ff0597d37f8aa8b",
          "sha256": "5c7ab3b6d73c31bab1fec22fe30a4e612afde13b240618cd9e3479bad80e5e97",
          "sha1": "a2767516b3ee2a140b4ff70c1c6de48130b9a471",
          "md5": "38895261dea8f28b4acc55f554a79d93"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency-mapper",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency-updater",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency-prebuilt",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-dependency-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 261,
          "sha512": "d82ce997efde752f0dfa6de421193dc1505f11d58e86843d6f31e203e34357da2ff048476e742935e0262757a76e1601633a1bae4b3d17939ff0597d37f8aa8b",
          "sha256": "5c7ab3b6d73c31bab1fec22fe30a4e612afde13b240618cd9e3479bad80e5e97",
          "sha1": "a2767516b3ee2a140b4ff70c1c6de48130b9a471",
          "md5": "38895261dea8f28b4acc55f554a79d93"
        }
      ]
    }
  ]
}
