{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-dependency-mapper",
    "version": "0.1.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-mapper-0.1.0-LOCAL.jar",
          "url": "toolkit-dependency-mapper-0.1.0-LOCAL.jar",
          "size": 514095,
          "sha512": "37e0e895c00f19507088439d5fff1ffcbcefb91f015f256d53c79c3df98b628ff2f3c9655f82f41ef438f87e50383d3bb6dad7155cdd3dbb2a3594c1179d67ab",
          "sha256": "df41b53ba5d302c6700a849c3440d134acc317710173f44fa37f91d8198fece2",
          "sha1": "a1e64f5cee305ca0b2bd4ab1744212ec6c2691dc",
          "md5": "30be0defee46b6814f0c6c6a7eeef540"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.tfowl.ktor",
          "module": "ktor-jsoup",
          "version": {
            "requires": "1.6.4",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "1.6.5",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.6.5",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.5",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.12.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "net.andreinc",
          "module": "mockneat",
          "version": {
            "requires": "0.4.7",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-mapper-0.1.0-LOCAL.jar",
          "url": "toolkit-dependency-mapper-0.1.0-LOCAL.jar",
          "size": 514095,
          "sha512": "37e0e895c00f19507088439d5fff1ffcbcefb91f015f256d53c79c3df98b628ff2f3c9655f82f41ef438f87e50383d3bb6dad7155cdd3dbb2a3594c1179d67ab",
          "sha256": "df41b53ba5d302c6700a849c3440d134acc317710173f44fa37f91d8198fece2",
          "sha1": "a1e64f5cee305ca0b2bd4ab1744212ec6c2691dc",
          "md5": "30be0defee46b6814f0c6c6a7eeef540"
        }
      ]
    }
  ]
}
