{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-dependency-updater",
    "version": "0.2.2-LOCAL-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-updater-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-dependency-updater-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 553901,
          "sha512": "fa87785c0ff05cd7ef82963faaa24595de96a11af26f4b1e0208149db95394b0a989bd86af07f27d6f3749182d7a3c829de590559cc1763e2a9099361d84f024",
          "sha256": "08024994da1ae857516530fc60fe823224963e4c3c06ba6a2e711ab32758f0fe",
          "sha1": "e39d7ba4ea731313a11450654b9c3a4c7771fbf3",
          "md5": "843788fc3dad1523b20187ba29c691bb"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-storage",
          "version": {
            "requires": "2.1.5",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.12.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0",
            "rejects": [
              "_"
            ]
          },
          "reason": "It has ready to use HttpException class"
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "strictly": "30.1.1-jre",
            "requires": "30.1.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-updater-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-dependency-updater-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 553901,
          "sha512": "fa87785c0ff05cd7ef82963faaa24595de96a11af26f4b1e0208149db95394b0a989bd86af07f27d6f3749182d7a3c829de590559cc1763e2a9099361d84f024",
          "sha256": "08024994da1ae857516530fc60fe823224963e4c3c06ba6a2e711ab32758f0fe",
          "sha1": "e39d7ba4ea731313a11450654b9c3a4c7771fbf3",
          "md5": "843788fc3dad1523b20187ba29c691bb"
        }
      ]
    }
  ]
}
