{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-dependency-updater",
    "version": "0.1.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-updater-0.1.0-LOCAL.jar",
          "url": "toolkit-dependency-updater-0.1.0-LOCAL.jar",
          "size": 554452,
          "sha512": "2a13f4bbcea57691cfc6ac7dbec116b8211b651ee86a3853b3ff03bf1638bd2d2e6b0a1a236b4304ca9e8b69ad89854bb789bcf2054381693f30176a2bde7edc",
          "sha256": "763c94eb253206aad1b2d67cb7c6ec29255d3d8460c137c6143644b9b0db73d1",
          "sha1": "8999250f5e37fc7f270ff6dc319ec1870969b46a",
          "md5": "b61040df2386bd016e4782553b788d5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-storage",
          "version": {
            "requires": "2.2.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.12.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0",
            "rejects": [
              "_"
            ]
          },
          "reason": "It has ready to use HttpException class"
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-updater-0.1.0-LOCAL.jar",
          "url": "toolkit-dependency-updater-0.1.0-LOCAL.jar",
          "size": 554452,
          "sha512": "2a13f4bbcea57691cfc6ac7dbec116b8211b651ee86a3853b3ff03bf1638bd2d2e6b0a1a236b4304ca9e8b69ad89854bb789bcf2054381693f30176a2bde7edc",
          "sha256": "763c94eb253206aad1b2d67cb7c6ec29255d3d8460c137c6143644b9b0db73d1",
          "sha1": "8999250f5e37fc7f270ff6dc319ec1870969b46a",
          "md5": "b61040df2386bd016e4782553b788d5c"
        }
      ]
    }
  ]
}
