{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-dependency-updater",
    "version": "0.1.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-updater-0.1.0-LOCAL.jar",
          "url": "toolkit-dependency-updater-0.1.0-LOCAL.jar",
          "size": 567773,
          "sha512": "bbc0583b695af91b4c32115050d2062a65a1a3a50c80cc2193e425e8028ace546701a228ebd1ea0340e10e18ba070ee122654178521954084155920019244eb9",
          "sha256": "87e1504edd218fbc6fce3932ba11357863ea791b7a1bfeae6a2c6a6173d116f6",
          "sha1": "a355f14c78f36904b857c953eb5c783821550734",
          "md5": "53efbebcb9ecce081b31f62699bb53ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.google.cloud",
          "module": "google-cloud-storage",
          "version": {
            "requires": "2.2.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-kotlin",
          "version": {
            "requires": "1.12.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0",
            "rejects": [
              "_"
            ]
          },
          "reason": "It has ready to use HttpException class"
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-updater-0.1.0-LOCAL.jar",
          "url": "toolkit-dependency-updater-0.1.0-LOCAL.jar",
          "size": 567773,
          "sha512": "bbc0583b695af91b4c32115050d2062a65a1a3a50c80cc2193e425e8028ace546701a228ebd1ea0340e10e18ba070ee122654178521954084155920019244eb9",
          "sha256": "87e1504edd218fbc6fce3932ba11357863ea791b7a1bfeae6a2c6a6173d116f6",
          "sha1": "a355f14c78f36904b857c953eb5c783821550734",
          "md5": "53efbebcb9ecce081b31f62699bb53ae"
        }
      ]
    }
  ]
}
