{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-publisher",
    "version": "0.2.2-LOCAL-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.mbonnin.vespene",
          "module": "vespene-lib",
          "version": {
            "requires": "0.5",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "org.jetbrains.dokka.gradle.plugin",
          "version": {
            "requires": "1.5.30",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-publisher-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-publisher-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 178733,
          "sha512": "3abfef0b19d8d2afb152ee0c78501b09bfa25718468d62e8b9f5c29a8150f3cd521379998ddc1e8b10f62128bd5c1accf128eef4f1d2a8b46f2b8e924c0b33ab",
          "sha256": "e44f044f2003253468c5dcbb1dd3bac41291b44715255c75fad289f8d5b6fc4f",
          "sha1": "e6ffe9c1116713c98cc000b741709bda4e620164",
          "md5": "5bfae21986872c7dd212ae34e1a9cfb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "0.16.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "net.mbonnin.vespene",
          "module": "vespene-lib",
          "version": {
            "requires": "0.5",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "org.jetbrains.dokka.gradle.plugin",
          "version": {
            "requires": "1.5.30",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-publisher-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-publisher-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 178733,
          "sha512": "3abfef0b19d8d2afb152ee0c78501b09bfa25718468d62e8b9f5c29a8150f3cd521379998ddc1e8b10f62128bd5c1accf128eef4f1d2a8b46f2b8e924c0b33ab",
          "sha256": "e44f044f2003253468c5dcbb1dd3bac41291b44715255c75fad289f8d5b6fc4f",
          "sha1": "e6ffe9c1116713c98cc000b741709bda4e620164",
          "md5": "5bfae21986872c7dd212ae34e1a9cfb8"
        }
      ]
    }
  ]
}
