{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-dependency-mapper",
    "version": "0.2.2-LOCAL-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-mapper-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-dependency-mapper-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 513530,
          "sha512": "c020ec01f308fffb1316ae7dd916f1a5a4756a3cca2f44fec4898590405758b4cbb2580cdcf2e28c1f30c7d221457772e0f5f3bc08fc23c200a22dd0f11ba256",
          "sha256": "785312917ff94188ac3736a0e4454bfd5c2d2ae5a078e91e5d04c5900554970a",
          "sha1": "5b828ed4ef81006ce62668e81bbb738ca9c4d878",
          "md5": "95bb09e421f241e895780e2884d4f5ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.tfowl.ktor",
          "module": "ktor-jsoup",
          "version": {
            "requires": "1.6.4",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "1.6.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.6.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.11.18",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "net.andreinc",
          "module": "mockneat",
          "version": {
            "requires": "0.4.7",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-mapper-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-dependency-mapper-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 513530,
          "sha512": "c020ec01f308fffb1316ae7dd916f1a5a4756a3cca2f44fec4898590405758b4cbb2580cdcf2e28c1f30c7d221457772e0f5f3bc08fc23c200a22dd0f11ba256",
          "sha256": "785312917ff94188ac3736a0e4454bfd5c2d2ae5a078e91e5d04c5900554970a",
          "sha1": "5b828ed4ef81006ce62668e81bbb738ca9c4d878",
          "md5": "95bb09e421f241e895780e2884d4f5ba"
        }
      ]
    }
  ]
}
