{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-dependency-mapper",
    "version": "0.1.0-LOCAL-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-mapper-0.1.0-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-dependency-mapper-0.1.0-LOCAL-SNAPSHOT.jar",
          "size": 508955,
          "sha512": "376eb975e1cfd0277c05772c91501fc3e5f95d2bb1eba425ec74cfeb9d3b9a2c907a43daf250228e51ed6aa543d6d96df8838a91fb7ee12517beb76bc76df2ae",
          "sha256": "e6faa243f4da56573a0eb2dfd52ea0889f3e8d6f6f53586df95f3ba0b8038c57",
          "sha1": "d56c3c958ca698faf43c40d62e1ce038f277f7ab",
          "md5": "e2d7f673544a7be65e15372a61b66c10"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.tfowl.ktor",
          "module": "ktor-jsoup",
          "version": {
            "requires": "1.6.4",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "1.6.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "1.6.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "net.bytebuddy",
          "module": "byte-buddy",
          "version": {
            "requires": "1.11.18",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "net.andreinc",
          "module": "mockneat",
          "version": {
            "requires": "0.4.7",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-mapper-0.1.0-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-dependency-mapper-0.1.0-LOCAL-SNAPSHOT.jar",
          "size": 508955,
          "sha512": "376eb975e1cfd0277c05772c91501fc3e5f95d2bb1eba425ec74cfeb9d3b9a2c907a43daf250228e51ed6aa543d6d96df8838a91fb7ee12517beb76bc76df2ae",
          "sha256": "e6faa243f4da56573a0eb2dfd52ea0889f3e8d6f6f53586df95f3ba0b8038c57",
          "sha1": "d56c3c958ca698faf43c40d62e1ce038f277f7ab",
          "md5": "e2d7f673544a7be65e15372a61b66c10"
        }
      ]
    }
  ]
}
