@file:Suppress("MemberVisibilityCanBePrivate")

package com.meowool.toolkit.gradle

import DirectoryTarget
import DokkaFormat
import MavenLocalTarget
import PublicationData
import PublishingTarget
import SonatypeTarget
import org.gradle.api.Project
import org.gradle.plugin.devel.PluginDeclaration
import java.io.File
import java.nio.file.Path

/**
 * The extension for publishing publication.
 *
 * @author 凛 (https://github.com/RinOrz)
 */
class PublicationExtension(internal val project: Project) {

  /**
   * If the value is `true`, when the project has applied the [Publisher] plugin but is incompatible, a warning message
   * will be printed. If the value is `false`, no warning message is printed and the project is skipped.
   */
  var showIncompatibleWarnings: Boolean = true

  /**
   * The data of this publication.
   */
  val data: PublicationData = PublicationData(project)

  /**
   * Whether to sign the release version of this publication.
   *
   * For more details see [Gradle documentation](https://docs.gradle.org/current/userguide/signing_plugin.html).
   */
  var isSignRelease: Boolean = true

  /**
   * Whether to sign the snapshot version of this publication.
   *
   * For more details see [Gradle documentation](https://docs.gradle.org/current/userguide/signing_plugin.html).
   */
  var isSignSnapshot: Boolean = false

  /**
   * The output format of documents generated by dokka.
   *
   * This is related to the javadoc of the publication, [for more details](https://github.com/Kotlin/dokka).
   */
  var dokkaFormat: DokkaFormat = DokkaFormat.Html

  /**
   * The target of this publication to publishing to.
   */
  val target: MutableList<PublishingTarget> = mutableListOf(SonatypeTarget())

  /**
   * The plugin class for this Gradle plugin publication.
   *
   * If this value is `null`, it means this is a Maven publication, otherwise this publication will be regarded
   * as a Gradle plugin.
   *
   * @see PublicationData
   * @see PluginDeclaration.implementationClass
   */
  var pluginClass: String? = null

  /**
   * Configures the data of this publication with [configuration].
   */
  fun data(configuration: PublicationData.() -> Unit) = data.apply(configuration)

  /**
   * Signs the release version of this publication.
   *
   * For more details see [Gradle documentation](https://docs.gradle.org/current/userguide/signing_plugin.html).
   *
   * @param isSign Whether to sign release version.
   */
  fun signRelease(isSign: Boolean = true) {
    isSignRelease = isSign
  }

  /**
   * Signs the snapshot version of this publication.
   *
   * For more details see [Gradle documentation](https://docs.gradle.org/current/userguide/signing_plugin.html).
   *
   * @param isSign Whether to sign snapshot version.
   */
  fun signSnapshot(isSign: Boolean = true) {
    isSignSnapshot = isSign
  }

  /**
   * Sets the output [format] of documents generated by dokka.
   *
   * This is related to the javadoc of the publication, [for more details](https://github.com/Kotlin/dokka).
   */
  fun dokkaFormat(format: DokkaFormat) {
    dokkaFormat = format
  }

  /**
   * Adds a publishing [target] for this publication.
   */
  fun publishTo(vararg target: PublishingTarget) {
    this.target += target
  }

  /**
   * Adds a target to publish this publication to the Maven Local repository.
   *
   * @see MavenLocalTarget
   */
  fun publishToMavenLocal() = publishTo(MavenLocalTarget)

  /**
   * Adds a target to publish this publication to the repository of specified directory.
   *
   * @param releasesPath The directory path to releases repository.
   * @param snapshotsPath The directory path to snapshots repository.
   *
   * @see DirectoryTarget
   */
  fun publishToDirectory(releasesPath: String, snapshotsPath: String = releasesPath) = publishTo(
    DirectoryTarget(releasesPath, snapshotsPath)
  )


  /**
   * Adds a target to publish this publication to the repository of specified directory.
   *
   * @param releases The directory path to releases repository.
   * @param snapshots The directory path to snapshots repository.
   *
   * @see DirectoryTarget
   */
  fun publishToDirectory(releases: Path, snapshots: Path = releases) = publishTo(
    DirectoryTarget(releases, snapshots)
  )

  /**
   * Adds a target to publish this publication to the repository of specified directory.
   *
   * @param releases The file (directory) to releases repository.
   * @param snapshots The file (directory) to snapshots repository.
   *
   * @see DirectoryTarget
   */
  fun publishToDirectory(releases: File, snapshots: File = releases) = publishTo(
    DirectoryTarget(releases, snapshots)
  )

  /**
   * Adds a target to publish this publication to the Sonatype OSS repository.
   *
   * @param s01 Publish to new url of Sonatype OSS, [see](https://central.sonatype.org/news/20210223_new-users-on-s01/)
   *
   * @see SonatypeTarget
   */
  fun publishToSonatype(s01: Boolean = true) = publishTo(SonatypeTarget(s01))
}