{
  "formatVersion": "1.1",
  "component": {
    "url": "../../multiplatform/0.1.0/multiplatform-0.1.0.module",
    "group": "com.meowool.gradle.test",
    "module": "multiplatform",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-debug.aar",
          "url": "multiplatform-android-debug-0.1.0.aar",
          "size": 1278,
          "sha512": "9804763989fd6c1265b0cc80e9ca92678efad23a7cb4c96f66b111763fe8ffc31570ecabd8d45d6bf503fc54667e30ee32314d402aad107c8bf994fa8ecb504f",
          "sha256": "678f353e4c07e260d7effc5236a29b3d410755d7935e0c3f9715bababdfc5d49",
          "sha1": "9e6ca11810995bb10f5915190d77eb67a0cec601",
          "md5": "62f56165d85d4dc006f560f5ba93e7e7"
        }
      ]
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-debug.aar",
          "url": "multiplatform-android-debug-0.1.0.aar",
          "size": 1278,
          "sha512": "9804763989fd6c1265b0cc80e9ca92678efad23a7cb4c96f66b111763fe8ffc31570ecabd8d45d6bf503fc54667e30ee32314d402aad107c8bf994fa8ecb504f",
          "sha256": "678f353e4c07e260d7effc5236a29b3d410755d7935e0c3f9715bababdfc5d49",
          "sha1": "9e6ca11810995bb10f5915190d77eb67a0cec601",
          "md5": "62f56165d85d4dc006f560f5ba93e7e7"
        }
      ]
    }
  ]
}
