{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-publishertoolkit-publisher",
    "version": "0.2.2-LOCAL-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.mbonnin.vespene",
          "module": "vespene-lib",
          "version": {
            "requires": "0.5",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.30",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-coretoolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-publishertoolkit-publisher-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-publishertoolkit-publisher-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 180049,
          "sha512": "1b2de08c665d41fc31f5b8fe24bf3981979af88c0f1cc80c160cf1513c85479a02479084fd2928174e72b382044672a4b54e181bc6fc76694f3b8dc8f205a1f9",
          "sha256": "22b89f0b5d1950ca756f42781cbf9dea633dcfcb6da3cd3676696f92bc38e482",
          "sha1": "cf986db8e2354e864d3666d1ca97dfafb8c7ba69",
          "md5": "43f1bf2b1e17d48fd97a772cffb81f01"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.gradle.publish",
          "module": "plugin-publish-plugin",
          "version": {
            "requires": "0.16.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "net.mbonnin.vespene",
          "module": "vespene-lib",
          "version": {
            "requires": "0.5",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.5.30",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-coretoolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-publishertoolkit-publisher-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-publishertoolkit-publisher-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 180049,
          "sha512": "1b2de08c665d41fc31f5b8fe24bf3981979af88c0f1cc80c160cf1513c85479a02479084fd2928174e72b382044672a4b54e181bc6fc76694f3b8dc8f205a1f9",
          "sha256": "22b89f0b5d1950ca756f42781cbf9dea633dcfcb6da3cd3676696f92bc38e482",
          "sha1": "cf986db8e2354e864d3666d1ca97dfafb8c7ba69",
          "md5": "43f1bf2b1e17d48fd97a772cffb81f01"
        }
      ]
    }
  ]
}
