{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit",
    "version": "0.1.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-android",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-meowool",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-publisher",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-0.1.0-LOCAL.jar",
          "url": "toolkit-0.1.0-LOCAL.jar",
          "size": 7637,
          "sha512": "5cfe1e79d99a7df6307a3edde683a2bc5f7bc07a43616519c8bddc0f46affd6b84f579f4bef6c83ab74dd428056a32e23c62947d7537a9c737a979c00e52bc99",
          "sha256": "d0b9b9a5d7c74ca856240ef7e502fb16333263ad3896be97e74e4775344da261",
          "sha1": "bd23a417556aea38bc04b51138c74dc2d09df814",
          "md5": "7fc0c42fe7fde35e4793f9d50abc9beb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-android",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-meowool",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-publisher",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-0.1.0-LOCAL.jar",
          "url": "toolkit-0.1.0-LOCAL.jar",
          "size": 7637,
          "sha512": "5cfe1e79d99a7df6307a3edde683a2bc5f7bc07a43616519c8bddc0f46affd6b84f579f4bef6c83ab74dd428056a32e23c62947d7537a9c737a979c00e52bc99",
          "sha256": "d0b9b9a5d7c74ca856240ef7e502fb16333263ad3896be97e74e4775344da261",
          "sha1": "bd23a417556aea38bc04b51138c74dc2d09df814",
          "md5": "7fc0c42fe7fde35e4793f9d50abc9beb"
        }
      ]
    }
  ]
}
