{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-android",
    "version": "0.2.2-LOCAL-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-android-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-android-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 789326,
          "sha512": "baec33d6d4c91d05f59b5b5dea35ab35f0fbc6a4190214b16b7392584ab01de422bd63ebc9967decc8c55eafc01dd6fde0e854a7b0a937bb67ff31f89e1d4b61",
          "sha256": "35e9e4085e3af86c54db8e41ce9cc6602a1e19d89875196945efafa0e46ea77c",
          "sha1": "2ca3b1ef1b917b59280cb77b9847283a09085a4a",
          "md5": "2a1e6979c137dbb282b95e8166391d86"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.0.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-android-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-android-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 789326,
          "sha512": "baec33d6d4c91d05f59b5b5dea35ab35f0fbc6a4190214b16b7392584ab01de422bd63ebc9967decc8c55eafc01dd6fde0e854a7b0a937bb67ff31f89e1d4b61",
          "sha256": "35e9e4085e3af86c54db8e41ce9cc6602a1e19d89875196945efafa0e46ea77c",
          "sha1": "2ca3b1ef1b917b59280cb77b9847283a09085a4a",
          "md5": "2a1e6979c137dbb282b95e8166391d86"
        }
      ]
    }
  ]
}
