{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-meowool-metalavatoolkit-meowool-metalava",
    "version": "0.2.2-LOCAL-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-coretoolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-metalavatoolkit-meowool-metalava-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-meowool-metalavatoolkit-meowool-metalava-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 48288,
          "sha512": "91c872281a1509087b89ba41b2f42900a26e9e09244564a541106e36af32b7216a3f19c758bfd94e0587047c0ab2c69592dc57f9aff60992ae95aba85ae93b70",
          "sha256": "eb21514a2bbbda95ac2517ec9690a4171d1ba4001903e23d8f2263e774cbb09a",
          "sha1": "91e123cc2424e133b8456d2d8e5b0143cc9f76fe",
          "md5": "2597b93db862426ca5bfa2d54b64d8a6"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-coretoolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-metalavatoolkit-meowool-metalava-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-meowool-metalavatoolkit-meowool-metalava-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 48288,
          "sha512": "91c872281a1509087b89ba41b2f42900a26e9e09244564a541106e36af32b7216a3f19c758bfd94e0587047c0ab2c69592dc57f9aff60992ae95aba85ae93b70",
          "sha256": "eb21514a2bbbda95ac2517ec9690a4171d1ba4001903e23d8f2263e774cbb09a",
          "sha1": "91e123cc2424e133b8456d2d8e5b0143cc9f76fe",
          "md5": "2597b93db862426ca5bfa2d54b64d8a6"
        }
      ]
    }
  ]
}
