{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle.test",
    "module": "jvm-test",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-test-0.1.0.jar",
          "url": "jvm-test-0.1.0.jar",
          "size": 261,
          "sha512": "b852b020a88a34824dedb3bbdcc9c2a7afe8018155508f4055a224c0fa312ffa39246dacba9f7bd0b60e6718319522618e3fad221e77341c8efd08159a374c4c",
          "sha256": "094658c09de541e8f993b3b8cfb3a500d80408435508252ba315cb8f2688b7c2",
          "sha1": "299a62273bd309e79408134e1c564c6a8c835cc8",
          "md5": "a58b76ad6d6429ca56b6a4bd24406430"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "jvm-test-0.1.0.jar",
          "url": "jvm-test-0.1.0.jar",
          "size": 261,
          "sha512": "b852b020a88a34824dedb3bbdcc9c2a7afe8018155508f4055a224c0fa312ffa39246dacba9f7bd0b60e6718319522618e3fad221e77341c8efd08159a374c4c",
          "sha256": "094658c09de541e8f993b3b8cfb3a500d80408435508252ba315cb8f2688b7c2",
          "sha1": "299a62273bd309e79408134e1c564c6a8c835cc8",
          "md5": "a58b76ad6d6429ca56b6a4bd24406430"
        }
      ]
    }
  ]
}
