{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-dependency-prebuilt",
    "version": "0.2.2-LOCAL-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency-mapper",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-prebuilt-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-dependency-prebuilt-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 128575,
          "sha512": "c0dfff6cbb969b6346a43f449ee0e5bdaf20658f764f282b8dcd577d2f5813fbf3b66e6749fa3ce6c2ca03a555df4536e790aa84a8978fa85fef26e286c7bd40",
          "sha256": "705c4d5e89c6cb3ca0ee2c1d7b3260f62629369a1c48738a723280483ef68c78",
          "sha1": "ce612b03af483f2f9b1fcaa102c0356d33c90b96",
          "md5": "d348a351113ba615715c97f5260f47d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-apache",
          "version": {
            "requires": "1.6.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-serialization",
          "version": {
            "requires": "1.6.3",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency-mapper",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-dependency-prebuilt-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-dependency-prebuilt-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 128575,
          "sha512": "c0dfff6cbb969b6346a43f449ee0e5bdaf20658f764f282b8dcd577d2f5813fbf3b66e6749fa3ce6c2ca03a555df4536e790aa84a8978fa85fef26e286c7bd40",
          "sha256": "705c4d5e89c6cb3ca0ee2c1d7b3260f62629369a1c48738a723280483ef68c78",
          "sha1": "ce612b03af483f2f9b1fcaa102c0356d33c90b96",
          "md5": "d348a351113ba615715c97f5260f47d8"
        }
      ]
    }
  ]
}
