{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-meowool",
    "version": "0.1.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-android",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-publisher",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-meowool-metalava",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "5.17.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-0.1.0-LOCAL.jar",
          "url": "toolkit-meowool-0.1.0-LOCAL.jar",
          "size": 108550,
          "sha512": "533ef33290bbe0e72b02e40dd7319f24fd6aa456b3d885380524b3b990fd3b94e998c07fe0b382d49faae08cf9b519528834504b5d664e6f7c7c6a2ded8e94e5",
          "sha256": "e0d962f43bb366e4beff53b3cf561273c2857351df38f863676e9d5eb4739310",
          "sha1": "28b491585cb210a1a1a324cd9cbc73e183428fe0",
          "md5": "b5dbad18790d204667a31841e12530b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-android",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-publisher",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-meowool-metalava",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "5.17.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-0.1.0-LOCAL.jar",
          "url": "toolkit-meowool-0.1.0-LOCAL.jar",
          "size": 108550,
          "sha512": "533ef33290bbe0e72b02e40dd7319f24fd6aa456b3d885380524b3b990fd3b94e998c07fe0b382d49faae08cf9b519528834504b5d664e6f7c7c6a2ded8e94e5",
          "sha256": "e0d962f43bb366e4beff53b3cf561273c2857351df38f863676e9d5eb4739310",
          "sha1": "28b491585cb210a1a1a324cd9cbc73e183428fe0",
          "md5": "b5dbad18790d204667a31841e12530b9"
        }
      ]
    }
  ]
}
