{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-meowool",
    "version": "0.1.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-android",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-publisher",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-meowool-metalava",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "5.15.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-0.1.0-LOCAL.jar",
          "url": "toolkit-meowool-0.1.0-LOCAL.jar",
          "size": 107955,
          "sha512": "fe6e49446827d93b06a62cc8373b4d2a6cce6f730334960590614b21814f1e587f7fc169a27f61ce1f7a9248eb3f4a9bf058eabee9360ff3d3d74922c96e6f07",
          "sha256": "9139fd68b1bf51931f5f8e4099976fe6a68d9cc7a65bbde6418bb5f3df8d270c",
          "sha1": "22da12abe98c1575379ac669b499e79fffb2f581",
          "md5": "14db1cba16ea5befe04141405ce37ca0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-android",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-publisher",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-meowool-metalava",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "5.15.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-0.1.0-LOCAL.jar",
          "url": "toolkit-meowool-0.1.0-LOCAL.jar",
          "size": 107955,
          "sha512": "fe6e49446827d93b06a62cc8373b4d2a6cce6f730334960590614b21814f1e587f7fc169a27f61ce1f7a9248eb3f4a9bf058eabee9360ff3d3d74922c96e6f07",
          "sha256": "9139fd68b1bf51931f5f8e4099976fe6a68d9cc7a65bbde6418bb5f3df8d270c",
          "sha1": "22da12abe98c1575379ac669b499e79fffb2f581",
          "md5": "14db1cba16ea5befe04141405ce37ca0"
        }
      ]
    }
  ]
}
