{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-meowool",
    "version": "0.1.0-LOCAL-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-android",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-publisher",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-meowool-metalava",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "5.15.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-0.1.0-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-meowool-0.1.0-LOCAL-SNAPSHOT.jar",
          "size": 107955,
          "sha512": "4b937dd912c2658ba0586feccc15306442f484caa49447d2ac6fffd87542b5a2031b780f5917df919b64808279ec4513c0275daaa0cd8a735f55c042a3d5b3ab",
          "sha256": "bdeff4d4ac7d370768986f4e3c7d4de5316b975480a605a7057c934c7565c3d7",
          "sha1": "0e0dd0ccd6c8c0415148c4ee098ba4e1fcf9decd",
          "md5": "a3f9a4808bc409f2c7ab5d5daa3ebec1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-android",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-dependency",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-publisher",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-meowool-metalava",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "5.15.1",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-0.1.0-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-meowool-0.1.0-LOCAL-SNAPSHOT.jar",
          "size": 107955,
          "sha512": "4b937dd912c2658ba0586feccc15306442f484caa49447d2ac6fffd87542b5a2031b780f5917df919b64808279ec4513c0275daaa0cd8a735f55c042a3d5b3ab",
          "sha256": "bdeff4d4ac7d370768986f4e3c7d4de5316b975480a605a7057c934c7565c3d7",
          "sha1": "0e0dd0ccd6c8c0415148c4ee098ba4e1fcf9decd",
          "md5": "a3f9a4808bc409f2c7ab5d5daa3ebec1"
        }
      ]
    }
  ]
}
