{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-meowool-metalava",
    "version": "0.1.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-metalava-0.1.0-LOCAL.jar",
          "url": "toolkit-meowool-metalava-0.1.0-LOCAL.jar",
          "size": 48207,
          "sha512": "89afae8e5f06807055cff3a60f64ff493679a406d25b57132016ac1c9dbcd616e3da0e8ba03a22817bc8eca42a757f1cb0cb09f0f82f8bcaee653fde793778d5",
          "sha256": "f3d17c815e3bc91112cdbbdfa956b48bb39277053e373bb815fe07f97424fb52",
          "sha1": "bce2edeefcc140ebc8e2396a1b9af12d304aaa43",
          "md5": "0231807f94a70b6f238e079c71803da1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-metalava-0.1.0-LOCAL.jar",
          "url": "toolkit-meowool-metalava-0.1.0-LOCAL.jar",
          "size": 48207,
          "sha512": "89afae8e5f06807055cff3a60f64ff493679a406d25b57132016ac1c9dbcd616e3da0e8ba03a22817bc8eca42a757f1cb0cb09f0f82f8bcaee653fde793778d5",
          "sha256": "f3d17c815e3bc91112cdbbdfa956b48bb39277053e373bb815fe07f97424fb52",
          "sha1": "bce2edeefcc140ebc8e2396a1b9af12d304aaa43",
          "md5": "0231807f94a70b6f238e079c71803da1"
        }
      ]
    }
  ]
}
