{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-meowool-metalava",
    "version": "0.1.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-metalava-0.1.0-LOCAL.jar",
          "url": "toolkit-meowool-metalava-0.1.0-LOCAL.jar",
          "size": 48708,
          "sha512": "cb2d0f33db3def666d46b0e8c11032b19a4c3b0aa34b3895da4517c936fe6b067374d7cae278d1f7aa0442af0312c4eba8c5278a84daa5e6ff36f20c07db939c",
          "sha256": "0162d9ba61430936ddd406561361eb2833f368bd7f58355ec8b0f8664c157da7",
          "sha1": "13de821fe73a65c30ec2c51394e8f4c7e62ef61a",
          "md5": "752a8be2571ae2f50022efb37c274dd5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0-RC",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-metalava-0.1.0-LOCAL.jar",
          "url": "toolkit-meowool-metalava-0.1.0-LOCAL.jar",
          "size": 48708,
          "sha512": "cb2d0f33db3def666d46b0e8c11032b19a4c3b0aa34b3895da4517c936fe6b067374d7cae278d1f7aa0442af0312c4eba8c5278a84daa5e6ff36f20c07db939c",
          "sha256": "0162d9ba61430936ddd406561361eb2833f368bd7f58355ec8b0f8664c157da7",
          "sha1": "13de821fe73a65c30ec2c51394e8f4c7e62ef61a",
          "md5": "752a8be2571ae2f50022efb37c274dd5"
        }
      ]
    }
  ]
}
