{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-meowool-metalava",
    "version": "0.1.0-LOCAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-metalava-0.1.0-LOCAL.jar",
          "url": "toolkit-meowool-metalava-0.1.0-LOCAL.jar",
          "size": 47388,
          "sha512": "86e54540b3eb9c3718a460316d5bec745fa6e90e294426d266a3457a5eb8b7d8537fdd561b5e46745478b7f59ac001d5533252bd1f93d7d9c12ea9cf5815b003",
          "sha256": "685b456293cfb448bd341343e25a14091fce615217e84dfc6cf31d88eaf4b82c",
          "sha1": "a01cac21ce789fcf57dd607ce7f04d4625d74958",
          "md5": "33af7db5e6694f08063cf4f2a91070eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.1.0-LOCAL"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "0.1.0-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-metalava-0.1.0-LOCAL.jar",
          "url": "toolkit-meowool-metalava-0.1.0-LOCAL.jar",
          "size": 47388,
          "sha512": "86e54540b3eb9c3718a460316d5bec745fa6e90e294426d266a3457a5eb8b7d8537fdd561b5e46745478b7f59ac001d5533252bd1f93d7d9c12ea9cf5815b003",
          "sha256": "685b456293cfb448bd341343e25a14091fce615217e84dfc6cf31d88eaf4b82c",
          "sha1": "a01cac21ce789fcf57dd607ce7f04d4625d74958",
          "md5": "33af7db5e6694f08063cf4f2a91070eb"
        }
      ]
    }
  ]
}
