{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-meowool-metalava",
    "version": "0.2.2-LOCAL-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-metalava-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-meowool-metalava-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 48207,
          "sha512": "cc4f94900243ccec93e93a926a89f1c5a4ba8f508115c7ad98f72b90d8c04c769f30ef8c49d9b9dbe5c3900b744d51d5aaa31b8f8f4f1262274a01d07b0744cf",
          "sha256": "55d93f8b5eb96cee9e376ffd2c4316a466cb1dc6fc1f5678a59d0041b7dbfe2d",
          "sha1": "30387eb7e8fb398ab441e348345c9d0b23e8c061",
          "md5": "a8e45310fe4b022e0e14499614abaf93"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-metalava-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-meowool-metalava-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 48207,
          "sha512": "cc4f94900243ccec93e93a926a89f1c5a4ba8f508115c7ad98f72b90d8c04c769f30ef8c49d9b9dbe5c3900b744d51d5aaa31b8f8f4f1262274a01d07b0744cf",
          "sha256": "55d93f8b5eb96cee9e376ffd2c4316a466cb1dc6fc1f5678a59d0041b7dbfe2d",
          "sha1": "30387eb7e8fb398ab441e348345c9d0b23e8c061",
          "md5": "a8e45310fe4b022e0e14499614abaf93"
        }
      ]
    }
  ]
}
