{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meowool.gradle",
    "module": "toolkit-meowool-metalava",
    "version": "0.2.2-LOCAL-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2-rc-3"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-metalava-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-meowool-metalava-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 48128,
          "sha512": "9d3de36825a49ed9a920e0f369b7534c30382078fb5aefb03e94baa8f2f3756b7194c3761089c9f69efdbecfe0aaae46448576c1a1871a61b91970d6efa67a85",
          "sha256": "998413d27314bfc7c156b459831cb9880ef71149c6f3681e642d1df0210609e2",
          "sha1": "47dfbf7f5ce14c1ead86eba21bb352ca7f9a1b5e",
          "md5": "4a98958e9e8eb0e9667ac24801eff76e"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.meowool.gradle",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.2-LOCAL-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.meowool.toolkit",
          "module": "sweekt",
          "version": {
            "requires": "1.24-SNAPSHOT",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-meowool-metalava-0.2.2-LOCAL-SNAPSHOT.jar",
          "url": "toolkit-meowool-metalava-0.2.2-LOCAL-SNAPSHOT.jar",
          "size": 48128,
          "sha512": "9d3de36825a49ed9a920e0f369b7534c30382078fb5aefb03e94baa8f2f3756b7194c3761089c9f69efdbecfe0aaae46448576c1a1871a61b91970d6efa67a85",
          "sha256": "998413d27314bfc7c156b459831cb9880ef71149c6f3681e642d1df0210609e2",
          "sha1": "47dfbf7f5ce14c1ead86eba21bb352ca7f9a1b5e",
          "md5": "4a98958e9e8eb0e9667ac24801eff76e"
        }
      ]
    }
  ]
}
